name: Salesforce CI/CD Pipeline TEST

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1

      - name: Create the server.key file from the secret variable SERVER_KEY
        run: echo "${{ secrets.SERVER_KEY }}" | base64 --decode > server.key

      - name: Authenticate to Salesforce
        run: |
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername --instanceurl ${{ secrets.SALESFORCE_instanceurl }}

      - name: Check for differences
        run: |
          sfdx force:source:status --targetusername ${{ secrets.SALESFORCE_USERNAME }}

      - name: Retrieve source from the org
        run: |
          sfdx force:source:retrieve --sourcepath force-app/main/default/ --targetusername ${{ secrets.SALESFORCE_USERNAME }}

      - name: Run Salesforce Tests
        run: |
          sfdx force:apex:test:run -r human -c -l RunLocalTests

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1

      - name: Authenticate to Salesforce
        run: |
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername --instanceurl ${{ secrets.SALESFORCE_instanceurl }}

      - name: Deploy changed source to the org
        run: |
          sfdx force:source:deploy --sourcepath force-app/main/default/ --targetusername ${{ secrets.SALESFORCE_USERNAME }}